### ISSUE TITLE
About the chin coordinate

### ISSUE THREAD

**Issue by Joooshua** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#10]
Just getting to know about MTCNN face landmark detection. Sorry to bother if it's a rookie question.

I am wondering how are the chin coordinates obtained. Isn't MTCNN can only generate 5 points (both eyes, nose tip and mouth corners) for one face?

Or should I use Dlib to obtain those coordinates?

**Comment by Joooshua** [comment]
could you please provide the code that is fine-tuned to get the sixth point?

**Comment by Oktai15** [comment]
@Joooshua you can use any 68-landmark detector and take from it coordinate for chin (e.g, this repo: https://github.com/1adrianb/face-alignment)

**Comment by Joooshua** [comment]
> @Joooshua you can use any 68-landmark detector and take from it coordinate for chin (e.g, this repo: https://github.com/1adrianb/face-alignment)

I thought there might be some other ways to change the output of the MTCNN. Thanks, though. I will try.
