### ISSUE TITLE
question: why do you convert the angles?

### ISSUE THREAD

**Issue by fogelton** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#13]
`eulerAngles = cv2.decomposeProjectionMatrix(proj_matrix)[6]
pitch, yaw, roll = [math.radians(_) for _ in eulerAngles]
pitch = math.degrees(math.asin(math.sin(pitch)))
roll = -math.degrees(math.asin(math.sin(roll)))
yaw = math.degrees(math.asin(math.sin(yaw)))`

eulerAngles are already in degrees, so why do you convert them to radian, do the sin and asin and convert them back to degrees? What point am I missing?
thanks

**Comment by jerryhouuu** [comment]
Because Euler Angles is not intuitive to me compared to Degree (angle). >_<
