### ISSUE TITLE
6 landmark feature points

### ISSUE THREAD

**Issue by Cydia2018** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#14]
Thanks for your work. Could you tell me more about "fine-tune the MTCNN into the output of 6 landmark feature points"? Usually, the output of MTCNN is only 5 landmark points.

**Comment by jerryhouuu** [comment]
Because MTCNN is only generate 5 landmark points, need to fine-tune.
