### ISSUE TITLE
where to get /home/jerry/Documents/test/test/landmark.txt

### ISSUE THREAD

**Issue by mansonami** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#2]
where to get /home/jerry/Documents/test/test/landmark.txt?  OR
what do you  calc the number in landmark with ?

**Comment by jerryhouuu** [comment]
@mansonami 
I got landmarks through MTCNN's Output,
I fine-tuned the MTCNN to 6 landmarks(more chin) from 5 landmarks.

**Comment by mansonami** [comment]
do you know the paramets flags=cv2.CV_ITERATIVE in cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.CV_ITERATIVE).
what should be in py3, is it flags=cv2.SOLVEPNP_ITERATIVE?

**Comment by pribadihcr** [comment]
@jerryhouuu,

Can you provide code for finetuned mtcnn. Thanks

**Comment by gozhhu** [comment]
Hi jerry, could you please upload landmark.txt so that we can run it for testing? @jerryhouuu 
thx

**Comment by lynnw123** [comment]
> Hi jerry, could you please upload landmark.txt so that we can run it for testing? @jerryhouuu
> thx

+1

**Comment by jerryhouuu** [comment]
@gozhhu @Yinling-123 You can use some landmark labeling tool, like [NaturalIntelligence/imglab
](https://github.com/NaturalIntelligence/imglab) to get that landmark result.

The landmark.txt like following:
_[image_path, left_eyes_x, left_eyes_y, right_eyes_x, right_eyes_y, nose_x, nose_y, left_mouth_x, left_mouth_y, right_mouth_x, right_mouth_y, chin_x, chin_y]_

**Comment by FelixZhang7** [comment]
@jerryhouuu why add one more landmarks(chin)?

**Comment by huybg-1975** [comment]
> @jerryhouuu why add one more landmarks(chin)?

same question @jerryhouuu

**Comment by jerryhouuu** [comment]
@FelixZhang7 @huybg-1975 you can fine-tune MTCNN, dlib or 3ddfa to get six landmarks for it's total landmarks.
