### ISSUE TITLE
module 'cv2' has no attribute 'CV_ITERATIVE'

### ISSUE THREAD

**Issue by woshizhangcheng** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#3]
python 3.6, opencv 3.4

(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.CV_ITERATIVE)

module 'cv2' has no attribute 'CV_ITERATIVE'

**Comment by jerryhouuu** [comment]
My opencv version is 2.4.9.

**Comment by akaszynski** [comment]
Came here looking for an answer to this question and eventually found it, use ```cv2.cv2.SOLVEPNP_ITERATIVE``` instead of ```cv2.CV_ITERATIVE```

**Comment by KovenYu** [comment]
> Came here looking for an answer to this question and eventually found it, use `cv2.cv2.SOLVEPNP_ITERATIVE` instead of `cv2.CV_ITERATIVE`

thank you.
I use 3.2 and in my case it should be cv2.SOLVEPNP_ITERATIVE
