### ISSUE TITLE
how to approve the degrees(yaw, roll, pitch)

### ISSUE THREAD

**Issue by jhj7905** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#4]
Hello, @jerryhouuu 
Nowadays, i have been interested in the head pose estimation.
When i ran your code, i wondered that how did you confirm the degrees(yaw, roll, pitch)?
Could you tell me how to evaluate the degrees?
Thank you, in advance

**Comment by jerryhouuu** [comment]
@jhj7905 But  I was directly connected to the camera for testing, there was no accurate verification for evaluation.
