### ISSUE TITLE
why I got the wrong answers?

### ISSUE THREAD

**Issue by wqz960** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#6]
HI  I am very interesting in your project. But when I used your sample picture(pic 3 yaw=-41）, I got another answer.

` import cv2
import math
import numpy as np

def face_orientation(height, width, landmarks):
    #size = frame.shape #(height, width, color_channel)

    image_points = np.array([
                            (landmarks[4], landmarks[5]),     # Nose tip
                            (landmarks[10], landmarks[11]),   # Chin
                            (landmarks[0], landmarks[1]),     # Left eye left corner
                            (landmarks[2], landmarks[3]),     # Right eye right corne
                            (landmarks[6], landmarks[7]),     # Left Mouth corner
                            (landmarks[8], landmarks[9])      # Right mouth corner
                        ], dtype="double")

    

                        
    model_points = np.array([
                            (0.0, 0.0, 0.0),             # Nose tip
                            (0.0, -330.0, -65.0),        # Chin
                            (-165.0, 170.0, -135.0),     # Left eye left corner
                            (165.0, 170.0, -135.0),      # Right eye right corne
                            (-150.0, -150.0, -125.0),    # Left Mouth corner
                            (150.0, -150.0, -125.0)      # Right mouth corner                         
                        ])

    # Camera internals
 
    center = (width/2, height/2)
    focal_length = center[0] / np.tan(60/2 * np.pi / 180)
    camera_matrix = np.array(
                         [[focal_length, 0, center[0]],
                         [0, focal_length, center[1]],
                         [0, 0, 1]], dtype = "double"
                         )

    dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
    (success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.SOLVEPNP_ITERATIVE)#flags=cv2.SOLVEPNP_ITERATIVE

    
    axis = np.float32([[500,0,0], 
                          [0,500,0], 
                          [0,0,500]])
                          
    imgpts, jac = cv2.projectPoints(axis, rotation_vector, translation_vector, camera_matrix, dist_coeffs)
    modelpts, jac2 = cv2.projectPoints(model_points, rotation_vector, translation_vector, camera_matrix, dist_coeffs)
    rvec_matrix = cv2.Rodrigues(rotation_vector)[0]

    proj_matrix = np.hstack((rvec_matrix, translation_vector))
    eulerAngles = cv2.decomposeProjectionMatrix(proj_matrix)[6] 

    
    pitch, yaw, roll = [math.radians(_) for _ in eulerAngles]

    pitch = math.degrees(math.asin(math.sin(pitch)))
    roll = -math.degrees(math.asin(math.sin(roll)))
    yaw = math.degrees(math.asin(math.sin(yaw)))

    #return imgpts, modelpts, (str(int(roll)), str(int(pitch)), str(int(yaw))), (landmarks[4], landmarks[5])
    return pitch,roll,yaw

landmarks = [298,145,363,142,360,175,325,225,374,223,371,269]
height = 281-108
width = 402-205

pitch,roll,yaw = face_orientation(height, width, landmarks)
print(pitch,roll,yaw)`

I just use the six landmarks i already know, but the yaw is 3.415. i don't know why. can you provide me some advice . i am very appreciated

**Comment by AndreyStille** [comment]
> HI I am very interesting in your project. But when I used your sample picture(pic 3 yaw=-41）, I got another answer.
> 
> ` import cv2
> import math
> import numpy as np
> 
> def face_orientation(height, width, landmarks):
> #size = frame.shape #(height, width, color_channel)
> 
> ```
> image_points = np.array([
>                         (landmarks[4], landmarks[5]),     # Nose tip
>                         (landmarks[10], landmarks[11]),   # Chin
>                         (landmarks[0], landmarks[1]),     # Left eye left corner
>                         (landmarks[2], landmarks[3]),     # Right eye right corne
>                         (landmarks[6], landmarks[7]),     # Left Mouth corner
>                         (landmarks[8], landmarks[9])      # Right mouth corner
>                     ], dtype="double")
> 
> 
> 
>                     
> model_points = np.array([
>                         (0.0, 0.0, 0.0),             # Nose tip
>                         (0.0, -330.0, -65.0),        # Chin
>                         (-165.0, 170.0, -135.0),     # Left eye left corner
>                         (165.0, 170.0, -135.0),      # Right eye right corne
>                         (-150.0, -150.0, -125.0),    # Left Mouth corner
>                         (150.0, -150.0, -125.0)      # Right mouth corner                         
>                     ])
> 
> # Camera internals
> 
> center = (width/2, height/2)
> focal_length = center[0] / np.tan(60/2 * np.pi / 180)
> camera_matrix = np.array(
>                      [[focal_length, 0, center[0]],
>                      [0, focal_length, center[1]],
>                      [0, 0, 1]], dtype = "double"
>                      )
> 
> dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
> (success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.SOLVEPNP_ITERATIVE)#flags=cv2.SOLVEPNP_ITERATIVE
> 
> 
> axis = np.float32([[500,0,0], 
>                       [0,500,0], 
>                       [0,0,500]])
>                       
> imgpts, jac = cv2.projectPoints(axis, rotation_vector, translation_vector, camera_matrix, dist_coeffs)
> modelpts, jac2 = cv2.projectPoints(model_points, rotation_vector, translation_vector, camera_matrix, dist_coeffs)
> rvec_matrix = cv2.Rodrigues(rotation_vector)[0]
> 
> proj_matrix = np.hstack((rvec_matrix, translation_vector))
> eulerAngles = cv2.decomposeProjectionMatrix(proj_matrix)[6] 
> 
> 
> pitch, yaw, roll = [math.radians(_) for _ in eulerAngles]
> 
> 
> pitch = math.degrees(math.asin(math.sin(pitch)))
> roll = -math.degrees(math.asin(math.sin(roll)))
> yaw = math.degrees(math.asin(math.sin(yaw)))
> 
> #return imgpts, modelpts, (str(int(roll)), str(int(pitch)), str(int(yaw))), (landmarks[4], landmarks[5])
> return pitch,roll,yaw
> ```
> 
> landmarks = [298,145,363,142,360,175,325,225,374,223,371,269]
> height = 281-108
> width = 402-205
> 
> pitch,roll,yaw = face_orientation(height, width, landmarks)
> print(pitch,roll,yaw)`
> 
> I just use the six landmarks i already know, but the yaw is 3.415. i don't know why. can you provide me some advice . i am very appreciated

Have you find the solution? Please help because I've faced same issue
