### ISSUE TITLE
how to decide the model_points?

### ISSUE THREAD

**Issue by bruce0715** [jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV#9]
Hi,
I just wonder how should I decide the "model_points" in your model? Thx!

**Comment by jerryhouuu** [comment]
@bruce0715  hi Bruce, you can reference this [https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib](https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/)
